// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://apudlbkacvpxhphecwjr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwdWRsYmthY3ZweGhwaGVjd2pyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2Nzc2NzYsImV4cCI6MjA2ODI1MzY3Nn0.V0T0k7gdPNh_jMT846Ld4ecxE-OZDv_5exOYpDjOd5A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});